config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'doors#index'

  resources :doors, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/door.rb
class Door < ApplicationRecord

  def isopen?
    (self.kind == 'normal' || self.kind == 'gross')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doors_controller.rb
class DoorsController < ApplicationController
  def index
    @doors = Door.all.order(:number)
  end

  def show
    @door = Door.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doors/index.html.haml
.grid.calendario
  .col-1-1
    = image_tag 'titel.svg', class: 'titleimage'
  - @doors.each do |door|
    .col-1-3.mobile-col-1-3
      .content
        .day
          - if door.isopen?
            = image_tag "door0.jpg"
            .door{ class: door.kind }
              %h1= door.number
            .prize
              = link_to door_path(door) do
                = image_tag "door#{door.number}.jpg"
          - else
            = image_tag "door0.jpg"
            .door.zu
              %h1= door.number

:javascript
  $('.door').on('click', function(){
  $(this).toggleClass('open');
  });

app/views/doors/show.html.haml
.detail

  %h1= @door.title
  = link_to doors_path do
    = image_tag "detail#{@door.number}.jpg"
  %p= @door.content.html_safe

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title calendario
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0, user-scalable=no" }
    %meta{ name: "apple-mobile-web-app-capable", content: "yes" }
    %meta{ name: "apple-mobile-web-app-status-bar-style", content: "black" }
    %link{ href: asset_path("icon.png"), rel: "apple-touch-icon" }
  %body
    = yield